{
    "name": "Menú de Usuario Personalizado",
    "version": "18.0.5.0.2",
    "category": "Website",
    "summary": "Portal B2B moderno con navegación lateral y panel de pedidos avanzado",
    "depends": [
        "portal",
        "sale",
        "sale_stock",
        "account",
        "stock",
        "website_sale",
        "website_sale_wishlist",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/portal_layout.xml",
        "views/portal_home.xml",
        "views/portal_orders.xml",
        "views/portal_returns.xml",
        "views/portal_pages.xml",
        "views/portal_lists.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "mi_cuenta_extendida_usuario/static/src/scss/portal.scss",
            "mi_cuenta_extendida_usuario/static/src/js/portal_account.js",
            "mi_cuenta_extendida_usuario/static/src/js/wishlist_header.js",
            "mi_cuenta_extendida_usuario/static/src/js/product_lists.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
