from . import discuss_channel
from . import discuss_channel_member
from . import mail_message
from . import mail_thread
from . import models
from . import owa_account
from . import owa_allowlist
from . import owa_auto_reply
from . import owa_blacklist
from . import owa_broadcast_group
from . import owa_call_log
from . import owa_campaign
from . import owa_channel_label
from . import owa_community
from . import owa_customer360
from . import owa_group_session
from . import owa_newsletter
from . import owa_group_participant_event
from . import owa_health_issue
from . import owa_inbound_rule
from . import owa_satisfaction_score
from . import owa_standing_order
from . import owa_status_broadcast
from . import owa_tag_rule
from . import owa_chatbot
from . import owa_cloud_template
from . import owa_dashboard
from . import owa_inbound_dedupe
from . import owa_message
from . import owa_notification_rule
from . import owa_pending_pair
from . import owa_quick_reply
from . import owa_quick_reply_button
from . import owa_quick_reply_list
from . import owa_slash_command
from . import res_config_settings
from . import res_partner
from . import res_partner_phase26
